apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-saleor
    access: proxy
    url: http://monitoring-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "10s"
      httpMethod: POST
